### ISSUE TITLE
Clear icon cache for Dock before restarting

### ISSUE THREAD

**Issue by daften** [fubarhouse/ansible-role-macdock#9]
Sometimes my icon cache for dock is corrupt, giving me "weird" icons with the pencils with an A lower right. Clearing the icon cache fixes this problem. This command fixes it right now. Do you think it's worthwhile to add this, maybe with an option? If so, I'll make a PR :)
```bash
sudo find /private/var/folders/ -name com.apple.dock.iconcache -exec rm {} \;
```

Solution from https://gist.github.com/fabiofl/5873100
Update: it doesn't work on a high sierra machine.

**Comment by fubarhouse** [comment]
I've got some ideas of how this would work, however I firmly believe it it doesn't work on 10.12.2 and 10.12.3, then we're better off with a different implementation.

If you find a solution I'd be happy to draft it up. I'm doing some googling now which looks like it can work, but not reliably.

**Comment by aldanor** [comment]
Just stumbled upon this as well, any further ideas on this?

**Comment by fubarhouse** [comment]
@aldanor,

Last time I checked there was no 100% solution for this problem, but just hit and miss.

I can have another look around, but I am open to suggestions and PR's if you feel there's an 80% or higher success rate for one implementation.

**Comment by fubarhouse** [comment]
This looks tangible, though I can't speak for backwards compatibility.
* https://gist.github.com/fabiofl/5873100#gistcomment-1240299

I'm interested, but I'd prefer to find a non-sudo way to do this if anybody knows how. If not, I may continue to explore this soon with the use of sudo.

**Comment by daften** [comment]
I have this in an aliases file for bash:
```
# Clear the icon cache for Dock
alias dockiconclear='sudo find /private/var/folders/ -name com.apple.iconservices -exec rm -rf {} \;; sudo find /private/var/folders/ -name com.apple.dock.iconcache -exec rm -rf {} \;; sudo rm -rf /Library/Caches/com.apple.iconservices.store; echo "Now reboot the system"'
```

I just perform it manually when needed.

**Comment by fubarhouse** [comment]
In checking for `sudo`, it's actually no problem to add that because the role makes use of `sudo` already.

At which point would you ideally prefer to see caches cleared, and under which circumstances would the task be skipped (for idempotence)?

**Comment by fubarhouse** [comment]
@daften,

Sounds good - I'll add a task either before the grunt work when changes are detected or after when no action was taken. I can have this done tonight.

**Comment by fubarhouse** [comment]
@daften,

Feel free to check out branch `issue/9`.

If you're happy with the implementation let me know, and I'll get a PR in.

Feedback is important, so let me know if and why it wouldn't be suitable.

**Comment by daften** [comment]
For reference: https://github.com/fubarhouse/ansible-role-macdock/compare/master...issue/9

The become_user part in the first changed block is not needed I think, when become: yes is added without become_user, it's always root.

I'd also still add something to the documentation OR add another task to the clear cache handler that prints: please reboot if your dock icons are messed up. Otherwise: looks good, thanks! :)

**Comment by fubarhouse** [comment]
#17 Checks all the boxes here, and tests are passing.

Let me know if you're happy and we'll merge!

**Comment by daften** [comment]
Well, I'm clapping my hands, so the song says I'm happy ;)

**Comment by daften** [comment]
Thanks @fubarhouse !  ;)

**Comment by fubarhouse** [comment]
No problems 👍
